export const userKeys = {
  FULL_NAME: 'full_name',
  MESSAGE: 'message',
  REMAINING_ATTEMPTS: 'remaining_attempts',
  APPLICATION_ID: 'application_id',
  DM_CUSTOMER_ID: 'dmcustomer_id',
  PROSPECT_ID: 'prospect_id',
  OFFER_EXPIRY_DATE: 'offer_expiry_date',
  IS_COMPLETED: 'is_completed',
  IS_EXPIRED: 'is_expired',
  IS_USER_VALID: 'is_user_valid',
  IS_GIFT_CARD_REDEEMED: 'is_redeemed',
  REDEMPTION_EMAIL: 'redemption_email',
  REDEEM_CODE_AVAILABLE: 'redeem_code_available',
};
